// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

namespace EFMultiTenantElasticScale.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddUser : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Users",
                c => new
                {
                    UserName = c.String(nullable: false, maxLength: 128),
                    DisplayName = c.String(),
                })
                .PrimaryKey(t => t.UserName);
        }

        public override void Down()
        {
            DropTable("dbo.Users");
        }
    }
}
